### ISSUE TITLE
Not display on Frontend

### ISSUE THREAD

**Issue by guatman** [Wadaboa/woo-num-slider#1]
Hi,
This plugin seems to do exactly what I need, nice work.
I manage to set it up perfectly in the Dashboard, but I can't get it to display in the Frontend.
But I have created a simple "numeric" term (ex.: "3") in a Product Attribute ("Height") but it does not display the widget. On the other hand if I use the default Woocommerce widget, which displays the data with a list, it does display.
Any ideas?
Thanks,

**Comment by Wadaboa** [comment]
Hi,

Thank you for your feedback.

My guess is that you should add more than 1 numeric value to the attribute you want to use with the filter. Moreover, you should assign the attribute values to existing products: if I recall correctly, the widget does not display if there are no products with the associated attribute.

Let me know if you're able to fix the issue or if you need more help. Thanks,
Alessio.

**Comment by guatman** [comment]
Alessio,

Thank you for your tips.
Now its working fine... I needed to enter more values.

I think it would be a good feature to be able to add the unit (after the values) of the terms of the attribute directly in each widget.

Thanks again

**Comment by Wadaboa** [comment]
Glad to hear that it works :)

Good idea about the unit of measure. I'll leave this issue open and add the feature as soon as I have some spare time.

Thank you,
Alessio.

**Comment by Wadaboa** [comment]
Hi @guatman,

I finally managed to add the feature you asked for. I released version v0.2.1 of the package with the "Unit" display. Let me know if it works as you expected 😃 

Closing this issue. Thanks again,
Alessio.

**Comment by guatman** [comment]
Hi Allessio,

Thank you so much.
I'm going to implement  the new version.
I'll contact you if I have any problems ;)

Thanks again

Muchas gracias,

Un saludo!

*Juan Manuel Pérez Álvarez*
Programación y diseño web | Diseño gráfico | Fotografía
(+34) 666.474.465 (no usamos WhatsApp)
*Nuevo horario: 8:00 a 16:00*

http://studio.guatman.net
